<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateContactsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('contacts', function (Blueprint $table) {
            $table->id();
            $table->string('name', 255);
            $table->string('address', 255)->nullable()->default('');
            $table->string('city', 255)->nullable()->default('');
            $table->string('state', 255)->nullable()->default('');
            $table->string('zipcode', 255)->nullable();
            $table->string('phone', 255)->nullable()->default('');
            $table->string('email', 255)->nullable();
            $table->string('website', 255)->nullable();
            $table->string('contact', 255)->nullable()->default('');
            $table->text('notes')->nullable();
            $table->bigInteger('contact_type_id');
            $table->softDeletes();
            $table->nullableTimestamps();
            $table->bigInteger('created_by')->nullable();

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('contacts');
    }
}
